### ISSUE TITLE
HTTP Session Cluster

### ISSUE THREAD

**Issue by hendratommy** [quarkiverse/quarkus-primefaces#168]
Hi,

As far as I know, being stateless Quarkus doesn't have HTTP Session, so how do we use SessionScope in multi node cluster?
Any documentation to set this up?

Thanks,

**Comment by tandraschko** [comment]
you cant
Quarkus doesnt support bean passivation and they have no plans for it

**Comment by melloware** [comment]
Yep your Quarkus apps must be standalone apps.  If you need multiple instances of a particular app we handle this at our Load Balancer with "sticky bit" to always send the user to the same server once they log in.  If that server dies they load balancer will send them to another server however it forces the user to re-authenticate.   Its not that big of a deal for us because our servers almost never go down unless it is a planned outage and we do that off hours with little customers in the app.
